pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.logIn, name='logIn'),
    path('logout/', views.logOut, name='logOut'),
    path('signup/', views.signup, name='signUp'),
]

waittime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('users/', include('users.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField("publish date")

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

users/models.py
from django.db import models


# Create your models here.

users/forms.py
from django import forms
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect
from django.urls import reverse


class SignUp(forms.Form):
    username = forms.CharField(label='Username', max_length=20, required=True)
    passwordOne = forms.CharField(label='Password', max_length=20, widget=forms.PasswordInput, required=True)
    passwordTwo = forms.CharField(label='Confirm Password', max_length=20, widget=forms.PasswordInput, required=True)
    email = forms.CharField(label = 'Email',max_length=50, required=True)


class LogIn(forms.Form):
    username = forms.CharField(label="Username", max_length=20, required=True)
    password = forms.CharField(label='Password', max_length=20, widget=forms.PasswordInput, required=True)
    
            

        
    

pages/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    return render(request, 'pages/index.html')

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

from .models import Question, Choice

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes +=1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

users/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import SignUp, LogIn
from django.db.models import Max, Avg, Count

# Create your views here.
def index(request):
    return render(request, 'users/signup.html')

def signup(request):
    if request.method == 'POST':
        form = SignUp(request.POST)
        if form.is_valid():
            
            username = form.cleaned_data['username']
            passwordOne = form.cleaned_data['passwordOne']
            passwordTwo = form.cleaned_data['passwordTwo']
            email = form.cleaned_data['email']

            if passwordOne != passwordTwo:
                return render(request, 'users/signup.html', {'form': form, 'error_message': "Passwords do not match."})

            else:
                user = User.objects.filter(username = username).aggregate(Count('username'))
                if user['username__count'] == 0:
                    if ' ' in username: 
                        return render(request, 'users/signup.html', {'form': form, 'error_message': "Username cannot contain spaces."})
                    else:
                        #Create the user
                        newUser = User.objects.create_user(username = username, password=passwordOne)
                        newUser.save()
                        

                        #Redirect to active waits
                        return HttpResponseRedirect(reverse('users:logIn'))

                else: 
                    return render(request, 'users/signup.html', {'form': form, 'error_message': "Username is already taken."})
                

                
    else:
        form = SignUp()       
            
            
    return render(request, 'users/signup.html', {'form': form})

def logIn(request):
    if request.method == "POST":
        form = LogIn(request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            userAuth = authenticate(request, username = username, password = password)
            if userAuth is not None:
                login(request, userAuth)
                return HttpResponseRedirect(reverse('polls:index'))
            else:
                return render(request, 'users/login.html', {'form': form, "error_message": "Incorrect Username/Password"})

    else:
        form = LogIn()

    return render(request, 'users/login.html')

def logOut(request):
    if request.user.is_anonymous: 
        return HttpResponseRedirect(reverse('polls:index'))
    else: 
        logout(request)
        return HttpResponseRedirect(reverse('pages:index'))
    

pages/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>WaitTime</title>
</head>
<body style="background-color:black">
    <nav class="navbar navbar-dark bg-dark">
       <h3><a href="{% url 'pages:index' %}" style="color:white">Home</a></h3>
       <h3><a href="{% url 'polls:index' %}" style="color:white">Waits</a></h3>

       <!-- Changes buttons based on whether a user is logged in or not -->
       {%  if user.is_anonymous%}
       <h3><a href="{% url 'users:logIn' %}" style="color:white">Login</a></h3>

       {% else %}
       <h3><a href="{% url 'users:logOut' %}" style="color:white">Logout</a></h3>

       {% endif %}
    </nav>
    
    {% block content %}

    {% endblock %}

</body>
</html>

pages/templates/pages/index.html
{% extends 'base.html' %}

{% block content %}


<div>
<div class="container text-center m-auto">
    <br>
    <h1 style="color: white; margin-top: 3em">Welcome to WaitTime!</h1>
    <br>
    <h4 style="color: white">Tired of trying to guess how long you'll have to wait?</h4>
    <br>
    <a href="{% url 'polls:index' %}" class="btn btn-danger">Get Started!</a>
    </div>
</div>


{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
<br>
<!-- <a href="{% url 'polls:index' %}" class="btn btn-dark ml-3">Home</a> -->

{%  if not user.is_anonymous%}

<div class="container text-center">
<h1 style="color:white">{{question.question_text}}</h1>

{% if error_message %}
<p>{{error_message}}</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method=post >
{% csrf_token %}
{% for choice in question.choice_set.all %}
<div class="form-check">
    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
    <label for="choice{{ forloop.counter}}" style="color:white">{{choice.choice_text}}</label><br>
</div>
{% endfor %}
<input class="btn btn-danger" type="submit" value="Vote">

</form>
{% else%}
<div class="container text-center">
<h1 style="color:white"> Please login to vote.</h1>
</div>
{% endif %}

</div>

{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container text-center m-auto">
<br>
<h1 style="color:white">Welcome to WaitTime!</h1>
<h6 style="color:white">Vote on and view restaurant wait times!</h6>
</div>
<br>
    {% if latest_question_list %}

        {% for question in latest_question_list %}
        
        <div class="border border-danger m-auto text-center" style="width: 20rem;">
            <div class="card-body">
                <h3 class="card-title" style="color:white">{{ question }}</h3>
                <a href="{% url 'polls:results' question.id %}" class="btn btn-danger">Wait Times</a>
            </div>
        </div>
        <br>

         {% endfor %}

        {% else %}
    {% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}

<br>
<!-- <a href="{% url 'polls:index' %}" class="btn btn-dark ml-3">Home</a> -->


<div class="border border-danger m-auto text-center" style="width: 20rem;">
    <div class="card-body">
    <h1 class="card-title" style="color:white">{{ question.question_text }}</h1>

        {% for choice in question.choice_set.all %}
        <p style="color:white">
            {{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}
        </p>
        {% endfor %}
        {%  if not user.is_anonymous%}
        <a href="{% url 'polls:detail' question.id %}" class="btn btn-danger">Insert Wait!</a>
        {% endif %}
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<br>
{% if error_message %}
<br>
<div class="container text-center m-auto">
<p>{{error_message}}</p>
</div>
<br>
{% endif %}
<br>
<div class="container text-center m-auto">
    <form action="{% url 'users:logIn' %}" method="POST">
        {% csrf_token %}
            <div class="form-group">
                <label style="color: white;">Username</label>
                <br>
                <input type="text" name="username">
            </div>
            <div class="form-group">
                <label style="color: white;">Password</label>
                <br>
                <input type="password" name="password">
            </div>
            <input type="submit" value="Log In">
    </form>
    <br>
    <a href="{% url 'users:signUp' %}">Don't have an account?</a>
    </div>

{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<br>
<div class="container text-center m-auto">
<p>{{error_message}}</p>
</div>
<br>
{% endif %}


<br>
<div class="container text-center m-auto">
<form action="{% url 'users:signUp' %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
            <label for="{{form.username.id_for_label" style="color: white;">Username</label>
            <br>
            {{form.username}}
        </div>
        <div class="form-group">
            <label for="{{form.passwordOne.id_for_label" style="color: white;">Password</label>
            <br>
            {{form.passwordOne}}
        </div>
        <div class="form-group">
            <label for="{{form.passwordTwo.id_for_label" style="color: white;">Confirm Password</label>
            <br>
            {{form.passwordTwo}}
        </div>
        <div class="form-group">
            <label for="{{form.email.id_for_label" style="color: white;">Email</label>
            <br>
            {{form.email}}
        </div>
        <input type="submit" value="Submit">
</form>
<br>
<a href="{% url 'users:logIn' %}">Already have an account?</a>
</div>

{% endblock %}